### ISSUE TITLE
@rpath/libG4OpenGL.dylib: Library not loaded

### ISSUE THREAD

**Issue by reginacaputo** [zoglauer/megalib#16]
I updated MEGAlib today. Everything compiled fine. geomega works no problem, no overlaps found (which uses cosima). When I try to generate a simulation file using Cosima. ie: 

>>Cosima source/UseCase1.source 

Based on your example file but with my geometry file. I get the following error: 
dyld: Library not loaded: @rpath/libG4OpenGL.dylib
  Referenced from: /Users/reginamcaputo/MEGAlib/bin/Cosima
  Reason: image not found
Trace/BPT trap: 5

I also get this if I just try executing Cosima (or cosima) without a file. Do you know what would be the cause? or how I can fix it? 

Thanks!

Here are my specs: 

Mac OS X 10.11.5 (El Capitan)
ROOT 6.06/02
Geant4 10.02

**Comment by zoglauer** [comment]
Hi Regina,

It looks like Geant4 failed to compile the OpenGL libraries
Could you check if there is a file called libG4OpenGL.XXX (either so or dylib) in the geant4/lib directory?

Thanks,
Andreas

**Comment by zoglauer** [comment]
Another question:
If you do 
geant4-config --libs
Do you see 
-lG4OpenGL
?

**Comment by reginacaputo** [comment]
Hi Andreas, 
Thanks for your quick response. I checked for the library file and found it in the geant4/lib directory (there was the dylib but not the so file): 

~/MEGAlib/external/geant4_v10.02.p02/lib/libG4OpenGL.dylib

When I run: geant4-config --libs

Here is the output: 
-L/Users/reginamcaputo/MEGAlib/external/geant4_v10.02.p02/bin/../lib -lG4OpenGL -lG4gl2ps -lG4Tree -lG4FR -lG4GMocren -lG4visHepRep -lG4RayTracer -lG4VRML -lG4vis_management -lG4modeling -lG4interfaces -lG4persistency -lG4analysis -lG4error_propagation -lG4readout -lG4physicslists -lG4run -lG4event -lG4tracking -lG4parmodels -lG4processes -lG4digits_hits -lG4track -lG4particles -lG4geometry -lG4materials -lG4graphics_reps -lG4intercoms -lG4global -lG4clhep -lG4expat -lG4zlib

Thanks,
Regina

**Comment by zoglauer** [comment]
Hi Regina,

I just verified, I do not get this error message on El Capitan 10.11.5 with Geant4 10.02.

Since it is rpath related, could you add the following line to src/cosima/Makefile:
Below the line starting with G4_LIBS add:
G4_LIBS    += -Wl,-rpath,$(shell geant4-config --prefix)

Then in the MEGAlib directory do:
make clean
make -j4
cosima

... and let me know how it goes.

Thanks,
Andreas

**Comment by reginacaputo** [comment]
Hi Andreas, 

Thanks for the steps. I followed your instructions (attached my Makefile -I added the .txt extension just so I could upload it to github- and the output after running make). And I still get the same error: 

cosima
dyld: Library not loaded: @rpath/libG4OpenGL.dylib
  Referenced from: /Users/reginamcaputo/MEGAlib/bin/cosima
  Reason: image not found
Trace/BPT trap: 5

Best, 
Regina

[make_output.txt](https://github.com/zoglauer/megalib/files/366338/make_output.txt)

[Makefile.txt](https://github.com/zoglauer/megalib/files/366340/Makefile.txt)

**Comment by zoglauer** [comment]
Hi Regina,

Could you send your complete environment, i.e. all the output when you issue the command "export"?
You can send it to my normal email, if you don't want it to appear here.

Thanks,
Andreas

**Comment by zoglauer** [comment]
Solution:
The problem originated from a screwed up bash environment.
Something corrupted the DYLD_LIBRARY_PATH & LD_LIBRARY_PATH's so that the correct path to the Geant4 lib directory was not included.

Both environment variable should contain a link to the Geant4 lib directory, such as
/home/andreas/Science/Software/MEGAlib/external/geant4_v10.02.p02/lib
or
/Users/andreas/Science/Software/MEGAlib/external/geant4_v10.02.p02/lib/Geant4-10.2.2/..

Using bash, one can verify it by looking at the output of:
export | grep LD_LIBRARY
