### ISSUE TITLE
If statement evaluation error

### ISSUE THREAD

**Issue by cbray0** [zoglauer/megalib#39]
When using an If statement to enable or disable portions of my geometry, I encountered an error when using for loops.

Code:
```
Name testGeometry
Version 0.0

Constant NLayers 0

If { NLayers > 0 }
   For I {NLayers} -1.0 1.0
       // Code
   Done
EndIf
```

Errors:
```
Loop number: 0
   ***  Error  ***   in setup file /home/cbray0/test.geo.setup at line 6:
"    For I {0} -1.0 1.0"
Loop number in for loop must be a positive integer
Stopping to scan geometry file!
```

Expected behavior:
Evaluate the condition of the if statement before the enclosed code.

Actual behavior:
Evaluates the enclosed code before the if statement condition

**Comment by zoglauer** [comment]
Thanks a lot for reporting this bug in so much detail.
I am able to reproduce it and can see where and how it happens.
It's not an easy fix, however. I'll keep you posted.

**Comment by zoglauer** [comment]
I added a temporary workaround to all current top branches: It does not give an error at the moment but only a warning.

The actual problem is more complex to fix.

However, it should not have an effect on the final geometry, as it only effects the expansion of the for-loop, not the actual execution of it.

**Comment by zoglauer** [comment]
Final fix in MEGAlib v4 (current branch: MEGAlib_v4-alpha)
